### ISSUE TITLE
Code Availability

### ISSUE THREAD

**Issue by null1024-ws** [cuhk-seclab/SelectFuzz#10]
I read your paper and you mentioned that about 2100 lines of C++ code are for distance calculation and selective instrumentaion. 
Is this part of code publicized?

**Comment by chluo911** [comment]
Yes. Distance calculation is implemented in \Adfuzz folder in the docker and selective instrumentation is implemented in [afl-llvm-pass.so.cc](https://github.com/cuhk-seclab/SelectFuzz/blob/master/llvm_mode/afl-llvm-pass.so.cc)

**Comment by null1024-ws** [comment]
Thanks for your quick response.
