### ISSUE TITLE
Artifacts link is broken

### ISSUE THREAD

**Issue by Vancir** [cuhk-seclab/SelectFuzz#16]
The link to artifacts is broken and we cannot access them anymore. Can you update the link? Thanks.

**Comment by chluo911** [comment]
Hi, can you try this one https://drive.google.com/file/d/1xe9KP3TIGMV-wpcKM1fM82sRiBmDKjUd/view?usp=sharing?

**Comment by Vancir** [comment]
It works now. Thank you so much.
