### ISSUE TITLE
Source code of libDFUZZPASS.so

### ISSUE THREAD

**Issue by Vancir** [cuhk-seclab/SelectFuzz#2]
Do you have a plan to open source the code of `libDFUZZPASS.so`?

**Comment by chluo911** [comment]
Thanks for your interests. The source code of libDFUZZPASS.so is not on github, but you can check it under directory /Adfuzz in Docker. The docker is released now. 

I would also suggest you run SelectFuzz in Docker. In some cases, the tool will not promt an error even if your environment are missing some dependencies.

**Comment by Vancir** [comment]
Thanks for your response. Sorry I didn't notice this folder. I can find the source code under /Adfuzz folder now.
