### ISSUE TITLE
Questions Regarding Selectfuzz Implementation

### ISSUE THREAD

**Issue by a2ure123** [cuhk-seclab/SelectFuzz#20]
Hello,

I am very interested in the Selectfuzz paper, but I currently have some questions. As I am reading through the code, I have been examining DFUZZPASS.cpp and afl-llvm-pass.so.cc in detail.

From my understanding, the process of Selectfuzz appears to be as follows: Initially, by compiling with afl-llvm-pass.so.cc, some relevant call and name information is generated. This information is then used to calculate distances. After recompiling with the distance information included, the MapDist is computed. My understanding is that MapDist indicates whether the current code block is getting closer to the target point, as mentioned in the paper regarding relevant code blocks. If MapDist decreases, it suggests that this code block is a relevant code block. Is my interpretation correct?

Additionally, the paper mentions that relevant code blocks need to analyze data flows, specifically those that change the values of key variables influencing the vulnerability trigger. Where is this implemented in the code?

Lastly, I would like to ask about how fuzzing implements path selection. For instance, if a new relevant code block is triggered, how does the system increase the mutation intensity?

Thank you for your assistance!

**Comment by chluo1997** [comment]
> From my understanding, the process of Selectfuzz appears to be as follows: Initially, by compiling with afl-llvm-pass.so.cc, some relevant call and name information is generated. This information is then used to calculate distances. After recompiling with the distance information included, the MapDist is computed. My understanding is that MapDist indicates whether the current code block is getting closer to the target point, as mentioned in the paper regarding relevant code blocks. If MapDist decreases, it suggests that this code block is a relevant code block. Is my interpretation correct?

Yes

> Additionally, the paper mentions that relevant code blocks need to analyze data flows, specifically those that change the values of key variables influencing the vulnerability trigger. Where is this implemented in the code?

It is implemented in [temporal-specialization](https://github.com/cuhk-seclab/SelectFuzz/blob/master/temporal-specialization). We use this tool to do data-flow analysis.

> Lastly, I would like to ask about how fuzzing implements path selection. For instance, if a new relevant code block is triggered, how does the system increase the mutation intensity?

You can check [afl-llvm-pass.so.cc](https://github.com/cuhk-seclab/SelectFuzz/blob/master/llvm_mode/afl-llvm-pass.so.cc). Basically, we record edge coverage of only relevant code.

**Comment by a2ure123** [comment]
Thanks for your clear explanation. I now have a better grasp of the tool's design and will study the details further. Appreciate your help!
