### ISSUE TITLE
Hello, I have some question For SelectFuzz.

### ISSUE THREAD

**Issue by hyjun0407** [cuhk-seclab/SelectFuzz#9]
I read your paper and this work is wonderful.
but I have some quick question.
1) Is Select Fuzz is Grey Fuzzer?
as far as i know, Grey Fuzzer is Working by Some feedback like Tracing Information without Source Code, But I only Can Find Fuzzing Example with Source code. If I wrong, Please Correct Me.

2) Same topic with question 1, is there are any Target Method with Function's Pointer? Ex) If A.c:3 is Crash(); and Crash Function's Pointer is 0xABCD, Can I Specific Target with Function's Pointer(0xABCD)? 

Thanks For Your Work, And May I ask You Your Contact? Thanks.

**Comment by chluo911** [comment]
1. Grey-box fuzzers like AFLGo and SelectFuzz operate on source code. Black-box fuzzers operate on binaries.
2. SelectFuzz can handle the cases where the fuzzing targets are in the functions called through function pointers, as it considers indirect calls when building the call graphs.

Sure. You can contact me through chluo@cse.cuhk.edu.hk
